import test from 'node:test';
import assert from 'node:assert/strict';
import {queryDiagnostic,BUILD_ID} from '../UnicomThreeCards.js';
import run from '../UnicomThreeCards.js';
import {mock,capture,phones,key} from './helpers.js';
async function seeded(){const m=mock();await capture(m);await run(m.ctx);const r=m.ctx.storage.getJSON(key(phones[0]));r.updatedAt=Date.now()-7200000;m.ctx.storage.setJSON(key(phones[0]),r);return m;}
const cases=[['HTTP',async()=>({status:500})],['TRANSPORT',async()=>{throw Error('https://private.example cookie=secret 13000000001');}],['JSON',async()=>({status:200,json:async()=>{throw Error('private body');}})],['DATA',async()=>({status:200,json:async()=>({code:'Y'})})],['DATA',async()=>({status:200,json:async()=>({code:'Y',feeResource:{feePersent:'private'},voiceResource:{},flowResource:{}})})]];
for(const [reason,get] of cases)test('safe diagnostic '+reason+' '+cases.indexOf(cases.find(x=>x[1]===get)),async()=>{const m=await seeded();const before=m.ctx.storage.getJSON(key(phones[0]));m.ctx.http.get=get;const r=await queryDiagnostic(m.ctx,1);assert.equal(r.source,'fallback_cache');assert.equal(r.reason,reason);assert.equal(r.updatedAt,before.updatedAt);assert.equal(r.httpStatus,reason==='HTTP'?500:reason==='TRANSPORT'?undefined:200);assert.ok(!JSON.stringify(r).match(/private|secret|13000000001|cookie/i));});
test('fresh cache makes zero HTTP calls and actual network is explicit',async()=>{const m=mock();await capture(m);const network=await queryDiagnostic(m.ctx,1);assert.equal(network.source,'network');assert.equal(network.reason,undefined);const n=m.calls.length;const cache=await queryDiagnostic(m.ctx,1);assert.equal(cache.source,'fresh_cache');assert.equal(m.calls.length,n);assert.equal(cache.updatedAt,network.updatedAt);assert.ok(BUILD_ID);});
test('save failure retains existing fallback semantics and original success time',async()=>{const m=await seeded();const old=m.ctx.storage.getJSON(key(phones[0]));m.ctx.storage.setJSON=()=>{throw Error('cookie=secret');};const r=await queryDiagnostic(m.ctx,1);assert.equal(r.reason,'STORAGE');assert.equal(r.source,'fallback_cache');assert.equal(r.updatedAt,old.updatedAt);});
for(const code of [401,403,'API'])test('auth invalidation unchanged '+code,async()=>{const m=await seeded();m.ctx.http.get=async()=>({status:code==='API'?200:code,json:async()=>({code:'N'})});const r=await queryDiagnostic(m.ctx,1);assert.equal(r.reason,code==='API'?'API':'AUTH');assert.equal(m.ctx.storage.getJSON(key(phones[0])).invalid,true);assert.equal(m.ctx.storage.getJSON(key(phones[0])).cookie,undefined);});
test('transport exception message cannot masquerade as API invalidation',async()=>{const m=await seeded();m.ctx.http.get=async()=>{throw Error('AUTH');};assert.equal((await queryDiagnostic(m.ctx,1)).reason,'TRANSPORT');assert.ok(m.ctx.storage.getJSON(key(phones[0])).cookie);});
test('three concurrent cards retain isolated query sources',async()=>{const m=await seeded();await capture(m,phones[1]);await capture(m,phones[2]);m.ctx.http.get=async u=>{if(u.includes(phones[0]))throw Error('private');return {status:500};};const r=await Promise.all([1,2,3].map(i=>queryDiagnostic(m.ctx,i)));assert.deepEqual(r.map(x=>x.reason),['TRANSPORT','HTTP','HTTP']);assert.deepEqual(r.map(x=>x.source),['fallback_cache','network','network']);});
